// app/layout.tsx
import type { Metadata } from 'next';
import './globals.css';
import Providers from './components/providers/Providers';
import { NavbarProvider } from './context/NavbarContext';
import LayoutWrapper from './LayoutWrapper';
import SideBarWrapper from './SideBarWrapper'; // নতুন wrapper

export const metadata: Metadata = {
  title: 'Task Management',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>
          <NavbarProvider>
            <div className="flex items-baseline justify-baseline gap-5">
              <SideBarWrapper />
              <LayoutWrapper>{children}</LayoutWrapper>
            </div>
          </NavbarProvider>
        </Providers>
      </body>
    </html>
  );
}
